# Generated by Django 4.2.16 on 2024-11-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='category name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date time')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliviries',
                'ordering': ['datetime'],
            },
        ),
    ]
